version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    target-branch: staging
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - synmux
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    cooldown:
      default-days: 7
    directory: /
    target-branch: staging
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - synmux
    groups:
      all-dependencies:
        patterns:
          - "*"
