[env]
AFFIRM_MISE_ACTIVE = "true"

[settings]
env_file = ".env"
disable_tools = ["aube", "bun", "npm", "yarn"]

[tools]
pnpm = { version = "12.8.1" }
node = { version = "26.10.0" }
rust = { version = "1.96.0" }

[tasks]
start = "pnpm run dev"
