[env]
AFFIRM_MISE_ACTIVE = "true"

[settings]
env_file = ".env"
disable_tools = ["npm", "pnpm", "yarn"]

[tools]
aube = { version = "2.2.17" }
node = { version = "26.10.0" }
rust = { version = "1.96.0" }

[tasks]
start = "bun dev"
