name: ci
on:
  pull_request: null
  push: null
permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  issues: write
  pull-requests: write
  security-events: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: pnpm and node
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
      - name: worker types are current
        run: git diff --exit-code -- worker-configuration.d.ts
      - name: trunk
        uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0
      - name: typecheck
        run: pnpm run lint:types
      - name: build
        run: pnpm run build
